### PR TITLE
Add websocket options to support the use of HTTP proxy.

### PR DESCRIPTION
**Pull request by kkushimoto**
How to use this options.
https://gist.github.com/kkushimoto/49a1f55a0384239a557376efed8ae730

### CODE REVIEW

**Comment by gkwicker** [comment]
Thanks for this pull request.  Can you tell us more about the use case?

**Comment by kkushimoto** [comment]
I cannot connect to the internet directly because I'm behind corporate HTTP proxy.
This PR enable devices to connect to the AWS IoT Server over proxy.

References
- AWS Developer forums: How do you use aws-iot-device-sdk from behind a corp. proxy?
    - https://forums.aws.amazon.com/thread.jspa?messageID=680373&#685967
- AWS JavaScript SDK supports proxy.
    - http://docs.aws.amazon.com/AWSJavaScriptSDK/guide/node-configuring.html#Configuring_a_Proxy

**Comment by gkwicker** [comment]
Thanks for the additional information, we understand your use case.  Our process for handling pull requests is to first incorporate them into our internal development process and then release them to GitHub once testing is complete.  Thanks for your contribution, and thanks for using AWS IoT.

**Comment by gkwicker** [comment]
Incorporated in [version 1.0.12](https://github.com/aws/aws-iot-device-sdk-js/releases/tag/v1.0.12)

**Pull request closed without merging**
