### PR TITLE
Update minimist

### PR DESCRIPTION
**Pull request by jmklix**
update minimist version to 1.2.6 because of security patch

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by bretambrose — APPROVED** [review]

**Comment by dreamorosi** [comment]
Thanks for the quick action, would you mind also please making a release so we can get the change via npm? Latest on npm is still 2.2.11 ([link](https://www.npmjs.com/package/aws-iot-device-sdk))

**Comment by TwistedTwigleg** [comment]
I just made a new release and it should be releasing to `npm` soon, latest by this time tomorrow 👍

**Comment by TwistedTwigleg** [comment]
The latest reason is out on `npm` 🎉

**Comment by dreamorosi** [comment]
Thanks a lot, really appreciate the responsiveness.

**Pull request merged**
