### PR TITLE
Allow mqtt over wss connection behind corporate proxy

### PR DESCRIPTION
**Pull request by ilyaext**

### CODE REVIEW

**Comment by ilyaext** [comment]
pull request created

**Comment by ilyaext** [comment]
Proxy URL is defined as: process.env.http_proxy = 'http://<proxy-address:port>'.
In case process.env.http_proxy isn't defined the connection is without proxy

**Comment by ilyaext** [comment]
I have tested the solution for proxy with username/password and it works. The following should be added to the client's script:
process.env.http_proxy ='http://proxy-address:port' ;
process.env.http_proxy_username = 'username';
process.env.http_proxy_password = 'password';

**Comment by h0ru5** [comment]
will this be merged?
there seem to be no blocking point in the discussions and corporate proxies are a common issue

**Comment by ilyaext** [comment]
As I understood it isn't merged. We use my change and it works. Please let me know what is required for to merge?

**Comment by justinboswell** [comment]
The best solution here is to hoist the code from ws.js into your user code creating the DeviceClient, by putting it into the options.websocketOptions that are passed to the DeviceClient ctor. Then it will be passed all the way through to the creation of the websocket. It's set up that way to enable you to configure for use cases such as this one.

**Comment by h0ru5** [comment]
@justinboswell this prohibits using certificate authentication on the **devices** behind a proxy as `wss` allows only SigV4 
 (yes, I am also deeply in love with that particular setup)

I managed to do it with some tricks here: https://gist.github.com/h0ru5/c226929b411bef95c47e8d7e86ee638c

**Pull request closed without merging**
